"""empty message

Revision ID: 041ee8ff31ef
Revises: 64b7751134d9
Create Date: 2021-01-07 22:37:54.814303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041ee8ff31ef'
down_revision = '64b7751134d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
