"""empty message

Revision ID: 667427605ec7
Revises: 6ebed6ea30db
Create Date: 2020-12-28 14:17:46.391353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667427605ec7'
down_revision = '6ebed6ea30db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
