"""empty message

Revision ID: 6ebed6ea30db
Revises: f7bcaa773074
Create Date: 2020-12-27 16:59:15.005902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebed6ea30db'
down_revision = 'f7bcaa773074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seek_venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seek_venue')
    # ### end Alembic commands ###
