"""empty message

Revision ID: d13f10d3a2e1
Revises: 522ac9fe93d5
Create Date: 2020-12-29 14:37:37.876809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13f10d3a2e1'
down_revision = '522ac9fe93d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###
